certManager:
  sourceNamespace: ""
  syncSecret: false
  targetNamespace: "org-*"

proxy:
  enabled: false

cluster:
  name: ""
  proxy:
    http: ""
    https: ""
    noProxy: ""

exclude:
  names:
  - "capi-*"
  - "dex-k8s-*"
