certManager:
  sourceNamespace: ""
  syncSecret: false
  targetNamespace: "org-*"

proxy:
  enabled: false

cluster:
  name: ""
  proxy:
    http: ""
    https: ""
    noProxy: ""

exclude:
  names:
  - "capi-*"
  - "dex-k8s-*"

wcIpCheck:
  enabled: false
  validationFailureAction: Enforce # or Audit
  infraClusterNames: # don't put general CAPI Cluster here, ip to this CR should be assigned by the infra controller
  - "VSphereCluster"
  controlPlaneIpRange:
    range: "" # explicit IP range from which the IPs can be set to WC's control planes (format: 10.10.222.230/29)
    # Following two options are used for calculating the range dynamically from the MC's control plane ip
    # result will be kubeadmConfig.data.ClusterConfiguration.controlPlaneEndpoint+offsetToMCControlPlaneIp/maskBits
    offsetToMCControlPlaneIp: 3 # this many IPs from the calculated range will be saved also for MC
    maskBits: 29 # used only when range is empty
  exclude:
    names: []
  installJob:
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    kubectlImage:
      registry: quay.io
      name: giantswarm/kubectl
      tag: 1.23.5
