version: 2.1

orbs:
  architect: giantswarm/architect@5.14.0

jobs:
  verify:
    docker:
    - image: cimg/base:2025.04
    steps:
    - checkout
    - run:
        name: Install Make
        command: |
          sudo apt-get update && sudo apt-get install make
    - run:
        name: Make verify
        command: |
          make verify

workflows:
  workflow:
    jobs:
    - verify:
          # Needed to trigger job also on git tag.
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-app-catalog:
        name: push-kyverno-policies-connectivity-to-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        attach_workspace: true
        chart: kyverno-policies-connectivity
        context: architect
          # Needed to trigger job also on git tag.
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        name: push-kyverno-policies-connectivity-to-capa-app-collection
        context: architect
        app_name: kyverno-policies-connectivity
        app_namespace: giantswarm
        app_collection_repo: capa-app-collection
        requires:
        - push-kyverno-policies-connectivity-to-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-kyverno-policies-connectivity-to-cloud-director-app-collection
        context: architect
        app_name: kyverno-policies-connectivity
        app_namespace: giantswarm
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-kyverno-policies-connectivity-to-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-kyverno-policies-connectivity-to-capz-app-collection
        context: architect
        app_name: kyverno-policies-connectivity
        app_namespace: giantswarm
        app_collection_repo: capz-app-collection
        requires:
        - push-kyverno-policies-connectivity-to-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/


    - architect/push-to-app-collection:
        name: push-kyverno-policies-connectivity-to-proxmox-app-collection
        context: architect
        app_name: kyverno-policies-connectivity
        app_namespace: giantswarm
        app_collection_repo: proxmox-app-collection
        requires:
        - push-kyverno-policies-connectivity-to-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-kyverno-policies-connectivity-to-vsphere-app-collection
        context: architect
        app_name: kyverno-policies-connectivity
        app_namespace: giantswarm
        app_collection_repo: vsphere-app-collection
        requires:
        - push-kyverno-policies-connectivity-to-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
