[[- if .Values.proxy.enabled ]]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-proxy-env
spec:
  rules:
    - name: inject-proxy-env-to-containers
      match:
        resources:
          kinds:
            - Pod
[[- if .Values.proxy.namespaces ]]
          namespaces:
          [[- range .Values.proxy.namespaces ]]
            - [[ . | quote ]]
          [[- end ]]
[[- end ]]
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "*"
                env:
                  [[- if .Secret.Values.proxy.http ]]
                  - name: HTTP_PROXY
                    value: [[ .Secret.Values.proxy.http ]]
                  - name: http_proxy
                    value: [[ .Secret.Values.proxy.http ]]
                  [[- end ]]
                  [[- if .Secret.Values.proxy.https ]]
                  - name: HTTPS_PROXY
                    value: [[ .Secret.Values.proxy.https ]]
                  - name: https_proxy
                    value: [[ .Secret.Values.proxy.https ]]
                  [[- end ]]
                  [[- if .Values.proxy.noProxy ]]
                  - name: NO_PROXY
                    value: [[ join "," .Values.proxy.noProxy ]]
                  - name: no_proxy
                    value: [[ join "," .Values.proxy.noProxy ]]
                  [[- end ]]
            =(initContainers):
              - (name): "*"
                env:
                  [[- if .Secret.Values.proxy.http ]]
                  - name: HTTP_PROXY
                    value: [[ .Secret.Values.proxy.http ]]
                  - name: http_proxy
                    value: [[ .Secret.Values.proxy.http ]]
                  [[- end ]]
                  [[- if .Secret.Values.proxy.https ]]
                  - name: HTTPS_PROXY
                    value: [[ .Secret.Values.proxy.https ]]
                  - name: https_proxy
                    value: [[ .Secret.Values.proxy.https ]]
                  [[- end ]]
                  [[- if .Values.proxy.noProxy ]]
                  - name: NO_PROXY
                    value: [[ join "," .Values.proxy.noProxy ]]
                  - name: no_proxy
                    value: [[ join "," .Values.proxy.noProxy ]]
                  [[- end ]]
            =(ephemeralContainers):
              - (name): "*"
                env:
                  [[- if .Secret.Values.proxy.HTTP ]]
                  - name: HTTP_PROXY
                    value: [[ .Secret.Values.proxy.http ]]
                  - name: http_proxy
                    value: [[ .Secret.Values.proxy.http ]]
                  [[- end ]]
                  [[- if .Secret.Values.proxy.https ]]
                  - name: HTTPS_PROXY
                    value: [[ .Secret.Values.proxy.https ]]
                  - name: https_proxy
                    value: [[ .Secret.Values.proxy.https ]]
                  [[- end ]]
                  [[- if .Values.proxy.noProxy ]]
                  - name: NO_PROXY
                    value: [[ join "," .Values.proxy.noProxy ]]
                  - name: no_proxy
                    value: [[ join "," .Values.proxy.noProxy ]]
                  [[- end ]]
[[- end ]]
